### ISSUE TITLE
loopclosing

### ISSUE THREAD

**Issue by liliang2655** [ApdowJN/Stereo-NEC#12]
大佬您好，您上传的源码中，是不是将ORB3里面的回环给注释了，同样的数据集，ORB3可以回环，但是您的源码回环不上，请问您是在哪里做了改动吗。期待您的回复

**Comment by ApdowJN** [comment]
Did you comment out the code at the end of the InitializeIMU function in LocalMapping.cc: 
{ unique_lock<mutex> lock(mMutexReset); mbBadImu = true; }?

**Comment by liliang2655** [comment]
> Did you comment out the code at the end of the InitializeIMU function in LocalMapping.cc: { unique_lock lock(mMutexReset); mbBadImu = true; }?

Yes, I had it repeat the initialization before, so you asked me to comment it out.#9  
Now it works fine, but it can't loop.

**Comment by ApdowJN** [comment]
Sounds good. I think it's not a big deal if the ATE is still accurate enough, even without a loop closing trigger.
