### ISSUE TITLE
ask where I can find the corresponding code for the 3-DOF BA

### ISSUE THREAD

**Issue by yinjhhust** [ApdowJN/Stereo-NEC#7]
Thank you for open-sourcing your work. Stereo-NEC is excellent. May I ask where I can find the corresponding code for the 3-DOF BA?

**Comment by ApdowJN** [comment]
Please refer to https://github.com/ApdowJN/Stereo-NEC/blob/c08452fe3bf6741e1c72142ec88b72f5cf2c731f/src/LocalMapping.cc#L1350 and https://github.com/ApdowJN/Stereo-NEC/blob/c08452fe3bf6741e1c72142ec88b72f5cf2c731f/src/G2oTypes.cc#L808 .
