### ISSUE TITLE
ask If only correspondences in left images are used for gyroscope bias estimation in open-source version

### ISSUE THREAD

**Issue by BITcats** [ApdowJN/Stereo-NEC#8]
Thanks for you outstanding work. I wonder if only correspondences in left images are used for gyroscope bias estimation in open-source version.
I find the part of the gyroscope bias estimator here:
https://github.com/ApdowJN/Stereo-NEC/blob/c08452fe3bf6741e1c72142ec88b72f5cf2c731f/src/Optimizer.cc#L3889
But I find only left features may be used for gyroscope bias estimation, because I can only find left features are tracked by opticalflow in open-source code:
https://github.com/ApdowJN/Stereo-NEC/blob/c08452fe3bf6741e1c72142ec88b72f5cf2c731f/src/Optimizer.cc#L3838

**Comment by ApdowJN** [comment]
In this release version, it only considers left images. The right image is similar, but using it would introduce extra time costs for keypoint tracking, outlier removal, etc. Additionally, the accuracy doesn't improve significantly. Therefore, in practice, we use information from the left camera only.

**Comment by BITcats** [comment]
Thanks for your reply. I wonder if the experiments (including accuracy and computation time tests) in the paper showed the results of this release version.

**Comment by ApdowJN** [comment]
Hi @BITcats, In the paper, Table 1 and Table 2 correspond to using information from a single camera. We found that using information from two cameras does not significantly improve accuracy but approximately doubles the runtime. Therefore, in practice, we only use information from a single camera (either left or right). By taking advantage of stereo images, we can obtain scaled landmarks for 3-DOF BA to estimate translation with scale.
